# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
The `x-bazis` extension of the OpenAPI operations generated by the route classes.
"""

import pytest

from bazis.core import introspect
from bazis.core.routes_abstract.initial import (
    OPENAPI_EXTENSION,
    InitialRouteBase,
    http_get,
    http_post,
)
from bazis.core.schemas.enums import RouteKind


PARENT = '/api/v1/entity/parent_entity'
PARENT_SET = 'entity.routes.ParentEntityRouteSet'


@pytest.fixture(scope='module')
def operations():
    from bazis.core.app import app

    return {
        (path, method.upper()): operation
        for path, item in app.openapi()['paths'].items()
        for method, operation in item.items()
    }


@pytest.mark.parametrize(
    'path, method, action, kind',
    [
        ('/', 'GET', 'action_list', 'collection'),
        ('/', 'POST', 'action_create', 'create'),
        ('/{item_id}/', 'GET', 'action_retrieve', 'item'),
        ('/{item_id}/', 'PATCH', 'action_update', 'update'),
        ('/{item_id}/', 'DELETE', 'action_destroy', 'delete'),
        ('/{item_id}/relationships/{related_field_name}', 'POST',
         'action_post_relationships', 'relationship'),
        ('/{item_id}/relationships/{related_field_name}', 'PATCH',
         'action_update_relationships', 'relationship'),
        ('/{item_id}/relationships/{related_field_name}', 'DELETE',
         'action_delete_relationships', 'relationship'),
        ('/schema_list/', 'GET', 'action_schema_list', 'schema'),
        ('/schema_create/', 'GET', 'action_schema_create', 'schema'),
        ('/{item_id}/schema_retrieve/', 'GET', 'action_schema_retrieve', 'schema'),
        ('/{item_id}/schema_update/', 'GET', 'action_schema_update', 'schema'),
        ('/route_filter_fields/', 'GET', 'get_route_filter_fields', 'schema'),
        ('/_id/', 'GET', 'action_list_id', 'other'),
    ],
)
def test_route_set_operations(operations, path, method, action, kind):
    assert operations[(PARENT + path, method)][OPENAPI_EXTENSION] == {
        'resource': 'entity.parent_entity',
        'route_set': PARENT_SET,
        'action': action,
        'kind': kind,
    }


def test_custom_action(operations):
    (path,) = [
        path for path, method in operations
        if path.endswith('/some_statics/') and method == 'GET'
    ]
    meta = operations[(path, 'GET')][OPENAPI_EXTENSION]
    assert meta['route_set'] == 'route_injection.routes.VehicleCarrierTaskRouteBase'
    assert meta['resource'] == 'route_injection.vehicle'
    assert (meta['action'], meta['kind']) == ('get_some_statics', 'other')


def test_operations_without_route_set(operations):
    assert OPENAPI_EXTENSION not in operations[('/api/healthcheck', 'GET')]


def test_matches_introspect(operations):
    """
    Every operation of a route class carries the facts of `bazis_introspect` about its
    route, and no other operation has the extension.
    """
    from bazis.core.app import app

    expected = {}
    for route_set in introspect.routes_info(app):
        for route in route_set['routes']:
            for method in route['methods']:
                expected[(route['path'], method)] = {
                    'resource': route_set['resource'],
                    'route_set': route_set['route_set'],
                    'action': route['action'],
                    'kind': route['kind'],
                }
    actual = {
        key: operation[OPENAPI_EXTENSION]
        for key, operation in operations.items()
        if OPENAPI_EXTENSION in operation
    }
    assert actual
    assert actual == {key: value for key, value in expected.items() if key in operations}
    assert {meta['kind'] for meta in actual.values()} == set(RouteKind)


class KindBase(InitialRouteBase):
    abstract = True

    @http_post('/', kind=RouteKind.CREATE)
    def action_make(self, **kwargs):
        pass

    @http_get('/plain/')
    def action_plain(self, **kwargs):
        pass


class KindRouteSet(KindBase):
    @http_post('/', openapi_extra={'x-other': 1})
    def action_make(self, **kwargs):
        pass

    @http_get('/{item_id}/', kind=RouteKind.ITEM)
    def action_plain(self, **kwargs):
        pass


def test_override_keeps_kind():
    """
    An override of a route keeps the kind of the route it overrides unless it declares
    its own; a route without a kind is `other`; the extension is added to `openapi_extra`.
    """
    assert KindBase.action_plain.kind is None
    assert KindRouteSet.action_make.kind is RouteKind.CREATE
    assert KindRouteSet.action_plain.kind is RouteKind.ITEM

    router = KindRouteSet.as_router()
    extra = {route.name: route.openapi_extra for route in router.routes}
    assert extra['KindRouteSet_action_make'] == {
        'x-other': 1,
        OPENAPI_EXTENSION: {
            'resource': None,
            'route_set': f'{__name__}.KindRouteSet',
            'action': 'action_make',
            'kind': 'create',
        },
    }


def test_default_kind():
    class PlainRouteSet(InitialRouteBase):
        @http_get('/')
        def action_any(self, **kwargs):
            pass

    assert PlainRouteSet.route_meta(PlainRouteSet.action_any)['kind'] == 'other'
