# Generated by Django 5.0.6 on 2024-06-27 14:35

from django.db import migrations, models

import bazis.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parententity',
            name='field',
            field=bazis.core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('first_field', 'First field'), ('second_field', 'Second field'), ('third_field', 'Third field')], max_length=32), blank=True, null=True, size=None, verbose_name='Field'),
        ),
        migrations.AddField(
            model_name='parententity',
            name='state',
            field=models.CharField(choices=[('state_one', 'State one'), ('state_two', 'State two'), ('state_three', 'State three'), ('state_four', 'State four')], default='state_one', max_length=255, verbose_name='State'),
        ),
    ]
