# Generated by Django 5.0.14 on 2025-10-01 09:15

import django.db.models.deletion
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_division_organization_driver_divisions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedEntityNull',
            fields=[
                ('extended_name', models.CharField(max_length=255)),
                ('extended_description', models.TextField(blank=True, null=True)),
                ('extended_is_active', models.BooleanField(default=True)),
                ('extended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extended_dt_approved', models.DateTimeField(blank=True, null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_entity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_entity_null', to='entity.parententity')),
            ],
            options={
                'verbose_name': 'Extended entity',
                'verbose_name_plural': 'Extended entities',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
