# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.14 on 2025-10-01 17:10

import django.db.models.deletion
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_extendedentitynull'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentEntityNull',
            fields=[
                ('dependent_name', models.CharField(max_length=255)),
                ('dependent_description', models.TextField(blank=True, null=True)),
                ('dependent_is_active', models.BooleanField(default=True)),
                ('dependent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dependent_dt_approved', models.DateTimeField(blank=True, null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_entities_null', to='entity.parententity')),
            ],
            options={
                'verbose_name': 'Dependent entity',
                'verbose_name_plural': 'Dependent entities',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
