# Generated by Django 5.0.1 on 2025-11-28 20:28

import django.db.models.deletion
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_dependententitynull'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithProtectedEntity',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.childentity')),
            ],
            options={
                'verbose_name': 'Entity with Protected',
                'verbose_name_plural': 'Entities with Protected',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
