# Generated by Django 5.0.14 on 2025-12-24 15:29

import django.db.models.deletion
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparse_fieldsets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sparse_fieldsets.category'),
        ),
    ]
