# Generated by Django 4.0.7 on 2022-09-26 12:39

from django.db import migrations

def create_extension(apps, schema_editor):
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")


def drop_extension(apps, schema_editor):
    schema_editor.execute("DROP EXTENSION IF EXISTS \"uuid-ossp\";")



class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_extension, reverse_code=drop_extension, atomic=True)
    ]

